Notebook 13 – Missing Values
=
Import Pandas and Create a Sample DataFrame

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": ["Arun", "Bala", "Chitra", "Deepa", "Ezhil"],
    "Age": [25, np.nan, 30, 28, np.nan],
    "Salary": [25000, 30000, np.nan, 40000, 35000]
})

print(df)

Check Missing Values — isnull()
=

In [ ]:
print(df.isnull())
print("\nMissing values per column:")
print(df.isnull().sum())

Check Non-Missing Values — notnull()
=

In [ ]:
print(df.notnull())

Remove Missing Values — dropna()
=

In [ ]:
print(df.dropna())

Fill Missing Values — fillna()
=

In [ ]:
df_filled = df.copy()

df_filled["Age"] = df_filled["Age"].fillna(
    df_filled["Age"].mean()
)
df_filled["Salary"] = df_filled["Salary"].fillna(
    df_filled["Salary"].mean()
)

print(df_filled.round(2))

Interpolate Missing Values — interpolate()
=

In [ ]:
data = pd.Series([10, 20, np.nan, 40, 50])

print(data.interpolate())

Missing Value Handling Strategies
=

dropna()
=
Remove missing rows or columns

fillna(0)
=
Replace missing values with zero

Mean imputation
=
Fill numerical values with the mean

Median imputation
=
Useful for skewed numerical data

Mode imputation
=
Fill categorical values with the most frequent value

interpolate()
=
Estimate missing values between known values

Forward fill
=
Use the previous valid value

Backward fill
=
Use the next valid value

Notebook 14 – Performance Optimization 
=

Vectorization
=

Vectorization performs operations on entire arrays or columns without writing an explicit Python loop.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Price": [100, 200, 300, 400],
    "Quantity": [2, 3, 4, 5]
})

df["Total"] = df["Price"] * df["Quantity"]

print(df)

apply() vs Loops
=
For simple numerical calculations, vectorized operations are usually preferable to apply() or explicit loops.    

In [ ]:
df = pd.DataFrame({"Marks": [45, 70, 85, 30]})

df["Result"] = df["Marks"].apply(
    lambda x: "Pass" if x >= 40 else "Fail"
)

print(df)

Memory Optimization
=

Use smaller numeric types only when they can represent all required values without overflow or loss of precision

In [ ]:
df = pd.DataFrame({
    "Age": [20, 25, 30, 35],
    "Salary": [20000, 25000, 30000, 35000]
})

print("Before optimization:")
print(df.dtypes)

df["Age"] = df["Age"].astype("int8")
df["Salary"] = df["Salary"].astype("int32")

print("\nAfter optimization:")
print(df.dtypes)

Category Data Type
=

Categorical data can reduce memory usage when a column has relatively few unique values repeated many times.    

In [ ]:
df = pd.DataFrame({
    "Department": [
        "IT", "HR", "IT", "Sales", "HR", "IT"
    ]
})

print("Before:")
print(df["Department"].dtype)

df["Department"] = df["Department"].astype("category")

print("\nAfter:")
print(df["Department"].dtype)

Efficient Pandas Practices
=

In [ ]:
Select only the columns you need
selected = df[["Department"]]

# Avoid unnecessary copies
# Use vectorized operations
# Read only required columns from a CSV
data = pd.read_csv(
    "employees.csv",
    usecols=["Name", "Salary"]
)

# Check memory usage
print(data.memory_usage(deep=True))

Notebook 15 – Mini Assessment
=
Create a NumPy Array
=

Definition: A NumPy array is a data structure used to store and perform operations on numerical data efficiently.

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data Type:", arr.dtype)

NumPy array vs Python list
=

In [ ]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

lst * 2    # [1, 2, 3, 1, 2, 3]
arr * 2    # array([2, 4, 6])

Broadcasting
=

Broadcasting lets NumPy operate on arrays of different shapes by virtually stretching the smaller one.
Shapes are compared from the right, and each pair of dimensions must be equal or one of them must be 1.


Definition: Broadcasting allows NumPy to perform operations on arrays of different shapes when their dimensions are compatible.

Real-world use: 
=

Adding a constant to every value in a dataset or normalizing data in machine learning.

In [ ]:
m = np.array([[1, 2, 3],
              [4, 5, 6]])        # shape (2, 3)
row = np.array([10, 20, 30])     # shape (3,)
col = np.array([[100], [200]])   # shape (2, 1)

m + row   # row added to each row
# [[11 22 33]
#  [14 25 36]]

m + col   # col added to each column
# [[101 102 103]
#  [204 205 206]]

Series vs DataFrame
=

A Series is a 1D labeled array (one column). A DataFrame is a 2D table of labeled columns, where each column is a Series and they share an index.



In [ ]:
s = pd.Series([10, 20, 30], index=["a", "b", "c"], name="score")

df = pd.DataFrame({
    "name": ["Asha", "Ben", "Chitra", "Dev"],
    "dept": ["AI", "AI", "Data", "Data"],
    "salary": [90, 85, np.nan, 70],
    "age": [28, 34, 41, 25],
})

type(df["salary"])    # Series
type(df[["salary"]])  # DataFrame

Read a CSV file
=
Definition:
=
pd.read_csv() loads data from a CSV file into a DataFrame.

Need to Make sure the CSV file exists in the specified path.
    

In [ ]:
df = pd.read_csv("data.csv")

# Common options
df = pd.read_csv(
    "data.csv",
    usecols=["name", "dept", "salary"],   # load only what you need
    dtype={"dept": "category"},
    parse_dates=["join_date"],            # if the column exists
    na_values=["NA", "?", ""],
    nrows=1000,                           # sample for quick checks
)

Merge two DataFrames
=
Definition:
=
pd.merge() combines two DataFrames using a common column or key.

In [ ]:
employees = pd.DataFrame({"emp_id": [1, 2, 3], "name": ["Asha", "Ben", "Chitra"]})
salaries  = pd.DataFrame({"emp_id": [1, 2, 4], "salary": [90, 85, 70]})

pd.merge(employees, salaries, on="emp_id", how="inner")  # only matching ids
pd.merge(employees, salaries, on="emp_id", how="left")   # all from employees
pd.merge(employees, salaries, on="emp_id", how="outer")  # everything

GroupBy and aggregation
=

Definition: 
=

groupby() groups rows based on a column, while aggregation calculates summary values such as sum, mean, and count.

In [ ]:
df.groupby("dept")["salary"].mean()

df.groupby("dept").agg(
    avg_salary=("salary", "mean"),
    max_age=("age", "max"),
    headcount=("name", "count"),
)

Filter rows on multiple conditions
=

Definition:
=
Boolean indexing filters rows using conditions. Use & for AND and | for OR, with each condition enclosed in parentheses.

Use & (and), | (or), ~ (not), and wrap each condition in parentheses.

In [ ]:
df[(df["dept"] == "AI") & (df["age"] > 30)]
df[(df["salary"] > 80) | (df["age"] < 26)]
df[df["dept"].isin(["AI", "Data"]) & ~df["salary"].isna()]
df.query("dept == 'AI' and age > 30")   # equivalent, more readable

Handle missing values
=

Definition:
=
Missing values are absent or unknown data, commonly represented as NaN in Pandas.

Prefer imputing with the median over the mean when the data is skewed. Always check why values are missing before dropping them.

In [ ]:
df.isna().sum()                              # count NaNs per column

df.dropna()                                  # drop rows with any NaN
df.dropna(subset=["salary"])                 # only if salary is NaN

df["salary"] = df["salary"].fillna(df["salary"].median())  # impute
df["dept"] = df["dept"].fillna("Unknown")

df["salary"] = df["salary"].ffill()          # forward fill (time series)
df["salary"] = df["salary"].interpolate()    # numeric interpolation

Statistical measures with NumPy
=
Definition:
=

NumPy provides functions to calculate summary statistics from numerical data.

In [ ]:
x = np.array([12, 15, 11, 18, 20, 14, 16])

np.mean(x)
np.median(x)
np.std(x)               # population std (ddof=0)
np.std(x, ddof=1)       # sample std
np.var(x, ddof=1)
np.min(x), np.max(x)
np.percentile(x, [25, 50, 75])
np.ptp(x)               # range (max - min)

y = np.array([2, 4, 3, 7, 9, 5, 6])
np.corrcoef(x, y)       # correlation matrix

m = np.array([[1, 2, 3], [4, 5, 6]])
m.mean(axis=0)          # per column
m.mean(axis=1)          # per row

Optimize a DataFrame for Memory Usage
=    

Definition: 
=

Memory optimization reduces the memory consumed by a DataFrame, which can improve efficiency when processing large datasets

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 25, 30, 35],
    "Department": ["IT", "HR", "IT", "HR"],
    "Salary": [25000, 30000, 35000, 40000]
})

before = df.memory_usage(deep=True).sum()

df["Age"] = df["Age"].astype("int8")
df["Salary"] = pd.to_numeric(
    df["Salary"], downcast="integer"
)
df["Department"] = df["Department"].astype("category")

after = df.memory_usage(deep=True).sum()

print("Memory Before:", before, "bytes")
print("Memory After:", after, "bytes")
print("Memory Saved:", before - after, "bytes")
print(df.dtypes)