Sprint 3 – NumPy & Pandas for AI/ML Engineers
=
Notebook 1 – Introduction to NumPy
=

What is NumPy?
=    

    NumPy (Numerical Python) is a Python library used for numerical computing. 
    It provides a powerful multidimensional array called ndarray and many mathematical functions    

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr)

Why NumPy?
=

NumPy is preferred for:
=

Fast numerical calculations

Handling large datasets

Multidimensional arrays

Mathematical and statistical operations

Linear algebra

Machine Learning and Data Science

Example:
=

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr * 2)

NumPy Arrays (ndarray)
=

ndarray means N-dimensional array.

In [ ]:
rr = np.array([10, 20, 30])
print(type(arr))

It can represent:
=    

1D array
2D array
3D or higher-dimensional arrays

Creating Arrays
=
    
From a list
=

        arr = np.array([1, 2, 3])
Zeros
=
        np.zeros(3) 
Ones
=
        np.ones(3) 
Range
=

        np.arange(1, 10, 2) 

Identity matrix
=

        np.eye(3)

Dimensions
=

Dimension represents the number of axes in an array.

In [ ]:
arr = np.array([[1, 2], [3, 4]])

print(arr.ndim)

Shape
=
shape tells us the size of the array along each dimension.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

Size
=

size returns the total number of elements.

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.size)

Data Types
=

NumPy arrays have a specific data type.

Common types:
=

int64
    
float64

bool

str

We can also specify the type:
=

arr = np.array([1, 2, 3], dtype=float)

print(arr)

In [ ]:
Indexing
=
Indexing accesses individual elements.

In [ ]:
arr = np.array([10, 20, 30, 40])

print(arr[0])
print(arr[2])

#or 2D arrays:

arr = np.array([[10, 20],
                [30, 40]])

print(arr[1, 0])

Slicing
=

Slicing extracts part of an array.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

Reshaping
=

reshape() changes the structure of an array without changing its data.

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)

Output:
=
[[1 2 3]
 [4 5 6]]
    
Flatten
=
flatten() converts a multidimensional array into a 1D array.

arr = np.array([[1, 2], [3, 4]])

flat = arr.flatten()

print(flat)

Output:
=
[1 2 3 4]
    
Copy vs View
=
Copy
=    

A copy creates a completely independent array.

arr = np.array([1, 2, 3])
copy_arr = arr.copy()

copy_arr[0] = 100

print(arr)

Output:
=

[1 2 3]
    
View
=    

A view shares the original array's data.

arr = np.array([1, 2, 3])
view_arr = arr.view()

view_arr[0] = 100

print(arr)

Output:
=

[100   2   3]

Key difference: Copy has independent data; View shares data.

Broadcasting
=    

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

arr = np.array([10, 20, 30])

print(arr + 5)

Output:
=
[15 25 35]

Here, 5 is automatically applied to every element.

Array Operations
=

NumPy supports element-wise operations.

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

Output:
=

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
    
Universal Functions — ufuncs
=    

Universal functions (ufuncs) operate element-by-element on NumPy arrays.

Examples:
=    

arr = np.array([1, 4, 9])

print(np.sqrt(arr))
print(np.square(arr))
print(np.exp(arr))

Other common ufuncs:
=    

np.sin()
np.cos()
np.log()
np.abs()
np.round()

Notebook 2 – NumPy Mathematical Operations
=


Sum
=

np.sum() calculates the total of array elements.


arr = np.array([10, 20, 30])


print(np.sum(arr))


Output:


60

Mean
=

Mean is the average value.

arr = np.array([10, 20, 30])

print(np.mean(arr))

Output:

20.0

Formula:
=

$$ Mean = \frac{\sum x}{n} $$

Median
=

Median is the middle value after sorting.


arr = np.array([10, 30, 20])


print(np.median(arr))


Output:
=

20.0

Median is useful when the data contains outliers.

Variance
=

Variance measures how much the data is spread around the mean.


arr = np.array([10, 20, 30])


print(np.var(arr))

\(Var(X) = E(X^2) - [E(X)]^2\)

For this normal curve with sigma 1.4, the identity above becomes

Var(X)=σ
2
=(1.4)
2
=1.96
σ
σ
μ
-σ
+σ
Value of X


Standard Deviation
=

Standard deviation measures the spread of values around the mean.

arr = np.array([10, 20, 30])

print(np.std(arr))

\(\sigma = \sqrt{\frac{1}{N}\sum_{i=1}^{N}(x_i-\mu)^2}\)

The points have mean μ = 5 and σ = 1.5.


Key point: Lower standard deviation means values are closer to the mean.

Minimum
=

np.min() returns the smallest value.


arr = np.array([10, 5, 30, 15])


print(np.min(arr))

Output:


5

Maximum
=

np.max() returns the largest value.


print(np.max(arr))


Output:


30

Argmin
=

argmin() returns the index of the minimum value.


arr = np.array([10, 5, 30, 15])


print(np.argmin(arr))


Output:


1

Because 5 is at index 1.

Argmax
=

argmax() returns the index of the maximum value.

print(np.argmax(arr))

Output:


2

Because 30 is at index 2.

Percentile
=

Percentile tells us the value below which a given percentage of observations falls.


arr = np.array([10, 20, 30, 40, 50])


print(np.percentile(arr, 50))

Output:


30.0

The 50th percentile is equivalent to the median.

Dot Product
=

The dot product multiplies corresponding elements and adds the results.

For:

A = [1, 2, 3]
B = [4, 5, 6]

The result is:

1×4 + 2×5 + 3×6 = 32



a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))

Output:

32

Matrix Multiplication
=

Matrix multiplication can be performed using np.matmul() or @.

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

Output:

[[19 22]
 [43 50]]

The multiplication follows the row × column rule.

A
2
1
3
4
0
2
×
B
5
2
1
4
3
7
=
AB
20
29
26
22
(AB)
11
	​

=(2⋅5)+(1⋅1)+(3⋅3)=20
Row
1
2
1
2
Column
1
2
1
2


Transpose
=

Transpose converts rows into columns and columns into rows.

A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A.T)

Output:


[[1 4]
 [2 5]
 [3 6]]
 
Basic Linear Algebra Operations
=

NumPy provides several linear algebra functions through np.linalg.

Matrix inverse
=
A = np.array([[1, 2],
              [3, 4]])

print(np.linalg.inv(A))

Determinant
=
print(np.linalg.det(A))

Eigenvalues
=    

values = np.linalg.eigvals(A)

print(values)

Norm
=    
v = np.array([3, 4])

print(np.linalg.norm(v))

Output:

5.0
    
Solving linear equations
=    
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

x = np.linalg.solve(A, b)

print(x)

| Topic                 | Purpose                             |
| --------------------- | ----------------------------------- |
| NumPy                 | Numerical computing library         |
| `ndarray`             | N-dimensional array                 |
| `shape`               | Dimensions of an array              |
| `size`                | Total number of elements            |
| `ndim`                | Number of dimensions                |
| Indexing              | Access individual elements          |
| Slicing               | Extract a portion of an array       |
| Reshape               | Change array structure              |
| Flatten               | Convert to 1D                       |
| Copy                  | Independent data                    |
| View                  | Shared data                         |
| Broadcasting          | Operations on compatible shapes     |
| ufunc                 | Element-wise mathematical operation |
| Sum                   | Total                               |
| Mean                  | Average                             |
| Median                | Middle value                        |
| Variance              | Measure of spread                   |
| Standard Deviation    | Spread around mean                  |
| Argmin                | Index of minimum                    |
| Argmax                | Index of maximum                    |
| Percentile            | Position-based statistical measure  |
| Dot Product           | Product of corresponding values     |
| Matrix Multiplication | Row × column multiplication         |
| Transpose             | Rows ↔ columns                      |
| `np.linalg`           | Linear algebra operations           |


Notebook 3 – NumPy Random Module
=

Random Numbers
=

Definition:
=
NumPy provides the numpy.random module to generate random numbers for simulations, testing, sampling, and machine learning.

In [ ]:
import numpy as np

numbers = np.random.rand(5)
print(numbers)

Random Seed
=

Definition:
=
A random seed makes random results reproducible. The same seed produces the same sequence of random numbers.

Use:
=

Testing

Debugging

Machine learning experiments

Reproducible results    

In [ ]:
import numpy as np

np.random.seed(42)

print(np.random.rand(5))

Random Integers
=
np.random.randint() generates random integer values.

Syntax:
=

     np.random.randint(low, high, size)

In [ ]:
import numpy as np

numbers = np.random.randint(1, 10, size=5)

print(numbers)

mportant: high is excluded.

np.random.randint(1, 10)

generates a number from 1 to 9.

Random Choice
=

np.random.choice() randomly selects values from an array.

In [ ]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

result = np.random.choice(data)

print(result)

Select multiple values:

result = np.random.choice(data, size=3)

print(result)

Possible output:

[20 50 10]

Example: Randomly selecting customers for a survey.

Shuffle
=

np.random.shuffle() randomly rearranges the elements of an array in-place.

The original array itself is modified.    

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

np.random.shuffle(data)

print(data)

Permutation
=

np.random.permutation() returns a new shuffled array.

| Feature        | `shuffle()`              | `permutation()`   |
| -------------- | ------------------------ | ----------------- |
| Original array | Modified                 | Not modified      |
| Returns        | `None`                   | New array         |
| Use            | Rearrange existing array | Get shuffled copy |


In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4, 5])

result = np.random.permutation(data)

print(result)
print(data)

Random Distributions
=

A probability distribution describes how random values are likely to occur.

NumPy provides many distributions.

Normal Distribution
=


import numpy as np

data = np.random.normal(
    loc=50,
    scale=10,
    size=5
)

print(data)


loc → mean
scale → standard deviation
size → number of values

Example: Student exam scores.

Uniform Distribution
=

All values within a specified range have equal probability

data = np.random.uniform(
    low=0,
    high=10,
    size=5
)

print(data)




Binomial Distribution
=

Used when there are a fixed number of independent trials with two possible outcomes.

 data = np.random.binomial(
    n=10,
    p=0.5,
    size=5
)

print(data)  

Example: 
=

Number of successful outcomes in 10 attempts.


Poisson Distribution
=

Used to model the number of events occurring within a fixed interval.

data = np.random.poisson(
    lam=3,
    size=5
)

print(data)

Example:
=

Number of customers arriving at a store per hour.   

Exponential Distribution
=

Used to model the time between events.

data = np.random.exponential(
    scale=2,
    size=5
)

print(data)

Example:
=

Waiting time between customer arrivals.    


Use in AI/ML:
=

Random functions are commonly used for sampling data, creating test datasets, simulations, initializing experiments, and splitting data randomly.    


    